"""
DeepEval Example

This script demonstrates how to integrate a local HuggingFace model (Gemma-3-1b-it)
into DeepEval. DeepEval is fundamentally built around pytest and unit-testing principles.

Run this with:
pytest deepeval_example.py
"""

import pytest
from deepeval import assert_test
from deepeval.test_case import LLMTestCase
from deepeval.metrics import AnswerRelevancyMetric
from deepeval.models.base_model import DeepEvalBaseLLM
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

class LocalGemmaModel(DeepEvalBaseLLM):
    """
    Wrapper for using a local model with DeepEval.
    DeepEval requires overriding load_model, generate, a_generate, and get_model_name.
    """
    def __init__(self, model_name="google/gemma-3-1b-it"):
        self.model_name = model_name
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        # Using bfloat16 for faster inference if supported
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name, 
            device_map="auto",
            torch_dtype=torch.bfloat16
        )

    def load_model(self):
        return self.model

    def generate(self, prompt: str) -> str:
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        outputs = self.model.generate(**inputs, max_new_tokens=100)
        return self.tokenizer.decode(outputs[0], skip_special_tokens=True)

    async def a_generate(self, prompt: str) -> str:
        # For simplicity, we wrap the synchronous generation.
        return self.generate(prompt)

    def get_model_name(self):
        return "Gemma-3-1b-it"

# Initialize our custom model.
# NOTE: Using a 1B model as a "judge" for AnswerRelevancy might be noisy. 
# In production, you might want to use a larger model or an API for the judge.
custom_model = LocalGemmaModel()

def test_answer_relevancy():
    # Provide the inputs to the test case
    test_case = LLMTestCase(
        input="What if these shoes don't fit?",
        # Actual output generated by our system (we could also generate this dynamically here)
        actual_output="We offer a 30-day full refund return policy.",
        # Retrieval context if evaluating RAG
        retrieval_context=["All items can be returned within 30 days for a full refund."]
    )

    # Initialize the metric, passing our custom local model to act as the judge.
    relevancy_metric = AnswerRelevancyMetric(
        threshold=0.5,
        model=custom_model,
        include_reason=True
    )

    # assert_test works like a standard pytest assertion, but computes the metric
    assert_test(test_case, [relevancy_metric])
